# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sesh < Formula
  desc ""
  homepage "https://github.com/ty-e-boyd/sesh"
  version "0.1.5"

  on_macos do
    on_intel do
      url "https://github.com/ty-e-boyd/sesh/releases/download/v0.1.5/sesh_Darwin_x86_64.tar.gz"
      sha256 "240b106f0213d6cdd9efe7170a5382be526bda3bfb683b5d57efc455f1072f90"

      def install
        bin.install "sesh"
      end
    end
    on_arm do
      url "https://github.com/ty-e-boyd/sesh/releases/download/v0.1.5/sesh_Darwin_arm64.tar.gz"
      sha256 "760dc0fc31636e28a5fbc85c6cdb1ff4106e8b7812ea1ac710650fe2471d0628"

      def install
        bin.install "sesh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ty-e-boyd/sesh/releases/download/v0.1.5/sesh_Linux_x86_64.tar.gz"
        sha256 "32d966e6ec141d7b8f6b771f49f6cd16275bcae69c1ab1fd3bf8586251470872"

        def install
          bin.install "sesh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ty-e-boyd/sesh/releases/download/v0.1.5/sesh_Linux_arm64.tar.gz"
        sha256 "a73a0afed5f7a416a3f1aa00e19b4ee9675730bf1e1a1300a54f5df749cdf9bf"

        def install
          bin.install "sesh"
        end
      end
    end
  end
end
