# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WeatherBro < Formula
  desc ""
  homepage "https://github.com/ty-e-boyd/weather-bro"
  version "1.0.5"

  on_macos do
    on_intel do
      url "https://github.com/ty-e-boyd/weather-bro/releases/download/v1.0.5/weather-bro_Darwin_x86_64.tar.gz"
      sha256 "e1f63e03d31be0b3cc3fb80acccc3d55af8825034ef12ad1b55333aeedda14e5"

      def install
        bin.install "weather-bro"
      end
    end
    on_arm do
      url "https://github.com/ty-e-boyd/weather-bro/releases/download/v1.0.5/weather-bro_Darwin_arm64.tar.gz"
      sha256 "f731393095949a7ad4cd1139c8293a09234b584233761b79110639328bd50ec6"

      def install
        bin.install "weather-bro"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ty-e-boyd/weather-bro/releases/download/v1.0.5/weather-bro_Linux_x86_64.tar.gz"
        sha256 "21ee3524b3788d8695425f909a2f440ce5c9524c044db75593126ef7cf8635b6"

        def install
          bin.install "weather-bro"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ty-e-boyd/weather-bro/releases/download/v1.0.5/weather-bro_Linux_arm64.tar.gz"
        sha256 "fb3aa3046ec6cc36468e347c167375b735deca2dada42704da74f2e26ba808f8"

        def install
          bin.install "weather-bro"
        end
      end
    end
  end
end
