# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WeatherBro < Formula
  desc ""
  homepage "https://github.com/ty-e-boyd/weather-bro"
  version "1.0.4"

  on_macos do
    on_intel do
      url "https://github.com/ty-e-boyd/weather-bro/releases/download/v1.0.4/weather-bro_Darwin_x86_64.tar.gz"
      sha256 "d7039dce30dc96f69a98040afb1bcee4a24d8d8c61830222f346ae0568d78777"

      def install
        bin.install "weather-bro"
      end
    end
    on_arm do
      url "https://github.com/ty-e-boyd/weather-bro/releases/download/v1.0.4/weather-bro_Darwin_arm64.tar.gz"
      sha256 "79e26dab3b6d7b130184d658e13868f5b4e3ee9b5e3af89226a9bd5015e08178"

      def install
        bin.install "weather-bro"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ty-e-boyd/weather-bro/releases/download/v1.0.4/weather-bro_Linux_x86_64.tar.gz"
        sha256 "c8ea981d2864c9595ff0ecddb32bf30301388395840df0b51709f716b6592029"

        def install
          bin.install "weather-bro"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ty-e-boyd/weather-bro/releases/download/v1.0.4/weather-bro_Linux_arm64.tar.gz"
        sha256 "8e38706a970cefcf39a627acecff78e8c94223f4cc8294c3d29d4cb9fcdb7517"

        def install
          bin.install "weather-bro"
        end
      end
    end
  end
end
